/**
 * 🧠 AMORSecondBrainManager — Second Brain Integration
 *
 * "The bridge between the contemplative present and the accumulated
 * wisdom of all your yesterdays. Where daily experience flows into
 * permanent knowledge, and the vault breathes with the rhythm of
 * intentional living."
 *
 * Reads from and writes to the Obsidian vault (or any markdown-based
 * second brain system). Generates daily summaries that can be filed
 * directly into the vault's daily notes structure.
 *
 * Architecture: Foundation-only. No SwiftUI. Fully type-checks with
 * swiftc -typecheck -sdk macosx. Uses filesystem-direct pattern.
 */

import Foundation

// MARK: - Vault Configuration

/// Represents the discovered Obsidian vault configuration.
struct VaultConfig: Codable {
    let name: String
    let path: String

    /// The daily notes directory, if it exists. Case-flexible: the canonical
    /// vault (~/wiki) uses lowercase `daily/`; other vaults may use `Daily/`.
    var dailyNotesURL: URL? {
        VaultConfig.firstExistingDir(in: URL(fileURLWithPath: path), names: ["daily", "Daily"])
    }

    /// The journal directory, if it exists
    var journalURL: URL? {
        VaultConfig.firstExistingDir(in: URL(fileURLWithPath: path), names: ["journal", "Journal"])
    }

    /// The EOD session-dump directory (raw/daily-summaries) — where the
    /// Hermes end-of-day dumper files `session-dump-YYYY-MM-DD.md`.
    var sessionDumpsURL: URL? {
        let url = URL(fileURLWithPath: path).appendingPathComponent("raw/daily-summaries")
        return FileManager.default.fileExists(atPath: url.path) ? url : nil
    }

    /// Returns the first existing subdirectory matching any of the given
    /// names (case-sensitive check in listed order — put the canonical
    /// lowercase form first).
    static func firstExistingDir(in parent: URL, names: [String]) -> URL? {
        for name in names {
            let url = parent.appendingPathComponent(name)
            if FileManager.default.fileExists(atPath: url.path) { return url }
        }
        return nil
    }
}

// MARK: - Daily Summary Structure

/// A structured daily summary ready for vault filing.
struct VaultDailySummary: Codable, Identifiable {
    let id: UUID
    let date: Date
    let sessionsLogged: Int
    let totalFocusMinutes: Int
    let tasksCompleted: Int
    let practicesCompleted: [String]
    let toolsUsed: [String]
    let skillsLearned: [String]
    let mood: String
    let reflection: String
    let topDomains: [String]
    let generatedAt: Date

    init(
        date: Date = .now,
        sessionsLogged: Int = 0,
        totalFocusMinutes: Int = 0,
        tasksCompleted: Int = 0,
        practicesCompleted: [String] = [],
        toolsUsed: [String] = [],
        skillsLearned: [String] = [],
        mood: String = "neutral",
        reflection: String = "",
        topDomains: [String] = [],
        generatedAt: Date = .now
    ) {
        self.id = UUID()
        self.date = date
        self.sessionsLogged = sessionsLogged
        self.totalFocusMinutes = totalFocusMinutes
        self.tasksCompleted = tasksCompleted
        self.practicesCompleted = practicesCompleted
        self.toolsUsed = toolsUsed
        self.skillsLearned = skillsLearned
        self.mood = mood
        self.reflection = reflection
        self.topDomains = topDomains
        self.generatedAt = generatedAt
    }

    /// Formats the summary as markdown for vault filing.
    func toMarkdown() -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd"
        let dateStr = formatter.string(from: date)

        formatter.dateStyle = .full
        let fullDate = formatter.string(from: date)

        let hours = Double(totalFocusMinutes) / 60.0

        var md = """
        # 📅 \(fullDate)

        > *Auto-generated by AMOR on \(formattedGenerated)*

        ## 📊 Session Summary
        - **Sessions logged:** \(sessionsLogged)
        - **Focus time:** \(String(format: "%.1f", hours)) hours (\(totalFocusMinutes) min)
        - **Tasks completed:** \(tasksCompleted)
        - **Mood:** \(mood)

        """

        if !practicesCompleted.isEmpty {
            md += "## 🧘 Practices Completed\n"
            for practice in practicesCompleted {
                md += "- ✅ \(practice)\n"
            }
            md += "\n"
        }

        if !toolsUsed.isEmpty {
            md += "## 🛠️ Tools Used\n"
            for tool in toolsUsed {
                md += "- \(tool)\n"
            }
            md += "\n"
        }

        if !skillsLearned.isEmpty {
            md += "## 📚 Skills & Learning\n"
            for skill in skillsLearned {
                md += "- \(skill)\n"
            }
            md += "\n"
        }

        if !topDomains.isEmpty {
            md += "## 🏷️ Domains\n"
            for domain in topDomains {
                md += "- \(domain)\n"
            }
            md += "\n"
        }

        if !reflection.isEmpty {
            md += "## 💭 Reflection\n\(reflection)\n\n"
        }

        md += """
        ---
        **Tags:** #daily #amor #session-dump #\(dateStr)
        """

        return md
    }

    private var formattedGenerated: String {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        formatter.timeStyle = .short
        return formatter.string(from: generatedAt)
    }
}

// MARK: - Second Brain Manager

/// Manages the connection between AMOR and the user's second brain system.
///
/// Auto-discovers Obsidian vaults from common locations. Supports
/// reading existing daily notes and writing new summaries.
@Observable
final class AMORSecondBrainManager {

    // MARK: - Published State

    /// Whether a vault was discovered
    var isVaultAvailable: Bool = false

    /// The discovered vault configuration
    var vault: VaultConfig?

    /// Recently written summaries (for dashboard card)
    var recentSummaries: [VaultDailySummary] = []

    /// Whether the last write succeeded
    var lastWriteSucceeded: Bool = false

    /// Status message for UI
    var statusMessage: String = "Searching for vault…"

    // MARK: - Init

    init() {
        discoverVault()
    }

    // MARK: - Vault Discovery

    /// Searches common locations for an Obsidian vault.
    /// v4.2.0: finds the canonical ~/wiki vault first, then falls back to
    /// Documents-based locations and a home-root .obsidian marker scan.
    func discoverVault() {
        let home = FileManager.default.homeDirectoryForCurrentUser

        // v4.2.0 — canonical vault first: ~/wiki (marked by .obsidian).
        var candidates: [URL] = [
            home.appendingPathComponent("wiki"),
            home.appendingPathComponent("Documents/Obsidian Vault"),
            home.appendingPathComponent("Documents/ObsidianVault"),
            home.appendingPathComponent("Obsidian Vault"),
            home.appendingPathComponent("Documents/vault"),
            home.appendingPathComponent("Documents/Vault"),
        ]

        // Also check for .obsidian directory markers in Documents
        let documentsDir = home.appendingPathComponent("Documents")
        if let contents = try? FileManager.default.contentsOfDirectory(at: documentsDir, includingPropertiesForKeys: nil) {
            for item in contents where item.hasDirectoryPath {
                let obsidianConfig = item.appendingPathComponent(".obsidian")
                if FileManager.default.fileExists(atPath: obsidianConfig.path) {
                    candidates.append(item)
                }
            }
        }

        // Only accept candidates that exist (~/wiki counts even without
        // .obsidian if it contains markdown; the marker check is a bonus).
        for candidate in candidates {
            let hasMarker = FileManager.default.fileExists(atPath: candidate.appendingPathComponent(".obsidian").path)
            let hasMarkdown = (try? FileManager.default.contentsOfDirectory(atPath: candidate.path))?.contains { $0.hasSuffix(".md") } ?? false
            if hasMarker || hasMarkdown {
                self.vault = VaultConfig(
                    name: candidate.lastPathComponent,
                    path: candidate.path
                )
                self.isVaultAvailable = true
                self.statusMessage = "Vault: \(vault?.name ?? "")"
                return
            }
        }

        self.isVaultAvailable = false
        self.statusMessage = "No Obsidian vault found"
    }

    // MARK: - Daily Note Filename

    /// Generates the daily note filename for a date (Obsidian default format).
    func dailyNoteFilename(for date: Date) -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd"
        return formatter.string(from: date) + ".md"
    }

    // MARK: - Read Existing Daily Notes

    /// Reads existing daily notes from the vault (last N days).
    func readDailyNotes(daysBack: Int = 7) -> [(date: Date, content: String, path: String)] {
        guard let vault = vault else { return [] }

        var results: [(date: Date, content: String, path: String)] = []
        let calendar = Calendar.current

        // v4.2.0 — case-flexible: canonical vault uses `daily/` (lowercase);
        // also check `Journal/`, then the vault root as a last resort.
        let searchDirs: [URL] = {
            var dirs: [URL] = []
            let vaultRoot = URL(fileURLWithPath: vault.path)
            for name in ["daily", "Daily", "journal", "Journal"] {
                let dir = vaultRoot.appendingPathComponent(name)
                if FileManager.default.fileExists(atPath: dir.path) {
                    dirs.append(dir)
                }
            }
            dirs.append(vaultRoot)
            return dirs
        }()

        for daysAgo in 0..<daysBack {
            if let date = calendar.date(byAdding: .day, value: -daysAgo, to: Date()) {
                let filename = dailyNoteFilename(for: date)

                for dir in searchDirs {
                    let fileURL = dir.appendingPathComponent(filename)
                    if let content = try? String(contentsOf: fileURL, encoding: .utf8) {
                        results.append((date: date, content: content, path: fileURL.path))
                        break // Found for this date
                    }
                }
            }
        }

        return results
    }

    // MARK: - Hermes EOD Session Dumps

    /// One parsed Hermes end-of-day session dump
    /// (~/wiki/raw/daily-summaries/session-dump-YYYY-MM-DD.md).
    struct HermesSessionDump: Identifiable {
        let date: Date
        let path: String
        let sessions: Int
        let messages: Int
        let toolCalls: Int
        let tools: [String]
        var id: Date { date }
    }

    /// Reads the Hermes EOD session dumps (newest first).
    /// These are generated by `~/.hermes/scripts/eod_session_dump.py` —
    /// the same ground truth the AMOR Ground Truth engine reads.
    func readHermesSessionDumps(daysBack: Int = 14) -> [HermesSessionDump] {
        guard let vault = vault else { return [] }
        let dumpsDir = URL(fileURLWithPath: vault.path)
            .appendingPathComponent("raw/daily-summaries")

        guard let files = try? FileManager.default.contentsOfDirectory(
            at: dumpsDir, includingPropertiesForKeys: nil
        ) else { return [] }

        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd"
        formatter.locale = Locale(identifier: "en_US_POSIX")

        var dumps: [HermesSessionDump] = []
        let cutoff = Calendar.current.date(byAdding: .day, value: -daysBack, to: Date()) ?? Date.distantPast

        for file in files where
            file.lastPathComponent.hasPrefix("session-dump-") && file.pathExtension == "md" {
            let datePart = file.deletingPathExtension().lastPathComponent
                .replacingOccurrences(of: "session-dump-", with: "")
            guard let date = formatter.date(from: datePart), date >= cutoff else { continue }
            guard let content = try? String(contentsOf: file, encoding: .utf8) else { continue }

            dumps.append(HermesSessionDump(
                date: date,
                path: file.path,
                sessions: Self.capturedInt(content, pattern: #"\*\*(\d+) sessions? today"#) ?? 0,
                messages: Self.capturedInt(content, pattern: #"Day totals:\*\* (\d+) messages"#) ?? 0,
                toolCalls: Self.capturedInt(content, pattern: #"(\d+) tool calls"#) ?? 0,
                tools: Self.toolsFromDump(content)
            ))
        }

        return dumps.sorted { $0.date > $1.date }
    }

    /// Extracts tools from a dump's `## Tools Used` table.
    private static func toolsFromDump(_ content: String) -> [String] {
        guard let range = content.range(of: "## Tools Used") else { return [] }
        let table = String(content[range.lowerBound...])
            .split(separator: "\n")
            .dropFirst()
            .prefix(while: { !$0.hasPrefix("**Models") && !$0.isEmpty })
        return table.compactMap { line in
            guard line.hasPrefix("| `") else { return nil }
            let name = line
                .replacingOccurrences(of: "| `", with: "")
                .split(separator: "`").first.map(String.init)
            return name
        }
    }

    /// First capture group of the first regex match, as an Int.
    private static func capturedInt(_ content: String, pattern: String) -> Int? {
        guard let regex = try? NSRegularExpression(pattern: pattern) else { return nil }
        let ns = content as NSString
        guard let m = regex.firstMatch(in: content, range: NSRange(location: 0, length: ns.length)),
              m.numberOfRanges > 1,
              let r = Range(m.range(at: 1), in: content) else { return nil }
        return Int(content[r])
    }

    // MARK: - Write Daily Summary

    /// Writes a daily summary to the vault as a daily note.
    /// If a note already exists for the date, appends AMOR data to it.
    func writeDailySummary(_ summary: VaultDailySummary) -> Bool {
        guard let vault = vault else {
            lastWriteSucceeded = false
            statusMessage = "No vault connected"
            return false
        }

        let vaultURL = URL(fileURLWithPath: vault.path)

        // v4.2.0 — write into the existing daily-notes directory, whatever
        // its casing. Only create `daily/` if no daily-notes dir exists yet.
        let dailyDir: URL
        if let existing = vault.dailyNotesURL {
            dailyDir = existing
        } else {
            dailyDir = vaultURL.appendingPathComponent("daily")
            try? FileManager.default.createDirectory(at: dailyDir, withIntermediateDirectories: true)
        }

        let filename = dailyNoteFilename(for: summary.date)
        let fileURL = dailyDir.appendingPathComponent(filename)

        let markdown = summary.toMarkdown()

        if FileManager.default.fileExists(atPath: fileURL.path) {
            // Append to existing note
            if let existing = try? String(contentsOf: fileURL, encoding: .utf8) {
                let separator = "\n\n---\n\n"
                let combined = existing + separator + markdown
                do {
                    try combined.write(to: fileURL, atomically: true, encoding: .utf8)
                    lastWriteSucceeded = true
                    statusMessage = "Appended to \(filename)"
                } catch {
                    lastWriteSucceeded = false
                    statusMessage = "Write failed: \(error.localizedDescription)"
                    return false
                }
            }
        } else {
            // Create new note
            do {
                try markdown.write(to: fileURL, atomically: true, encoding: .utf8)
                lastWriteSucceeded = true
                statusMessage = "Created \(filename)"
            } catch {
                lastWriteSucceeded = false
                statusMessage = "Write failed: \(error.localizedDescription)"
                return false
            }
        }

        // Track recent summaries
        recentSummaries.insert(summary, at: 0)
        if recentSummaries.count > 10 {
            recentSummaries = Array(recentSummaries.prefix(10))
        }

        return true
    }

    // MARK: - List All Vault Notes

    /// Returns a listing of all markdown notes in the vault.
    func listVaultNotes(limit: Int = 100) -> [(path: String, title: String, modified: Date)] {
        guard let vault = vault else { return [] }

        let vaultURL = URL(fileURLWithPath: vault.path)
        var results: [(path: String, title: String, modified: Date)] = []

        enumerateMarkdownFiles(in: vaultURL, results: &results, limit: limit)

        return results.sorted { $0.modified > $1.modified }
    }

    private func enumerateMarkdownFiles(in dir: URL, results: inout [(path: String, title: String, modified: Date)], limit: Int) {
        guard results.count < limit else { return }

        // Skip .obsidian and other hidden directories
        let dirname = dir.lastPathComponent
        if dirname.hasPrefix(".") || dirname == ".obsidian" || dirname == ".trash" {
            return
        }

        guard let contents = try? FileManager.default.contentsOfDirectory(at: dir, includingPropertiesForKeys: [.contentModificationDateKey, .isDirectoryKey]) else {
            return
        }

        for item in contents {
            let isDir = (try? item.resourceValues(forKeys: [.isDirectoryKey]).isDirectory) ?? false

            if isDir {
                enumerateMarkdownFiles(in: item, results: &results, limit: limit)
            } else if item.pathExtension == "md" {
                let modified = (try? item.resourceValues(forKeys: [.contentModificationDateKey]).contentModificationDate) ?? Date.distantPast
                let title = item.deletingPathExtension().lastPathComponent
                let relativePath = item.path.replacingOccurrences(of: vault!.path + "/", with: "")
                results.append((path: relativePath, title: title, modified: modified))

                if results.count >= limit { return }
            }
        }
    }

    // MARK: - Read Note Content

    /// Reads the content of a specific note by relative path.
    func readNote(path: String) -> String? {
        guard let vault = vault else { return nil }
        let url = URL(fileURLWithPath: vault.path).appendingPathComponent(path)
        return try? String(contentsOf: url, encoding: .utf8)
    }
}
