/**
 * 🧠 AMORSecondBrainManager — Second Brain Integration
 *
 * "The bridge between the contemplative present and the accumulated
 * wisdom of all your yesterdays. Where daily experience flows into
 * permanent knowledge, and the vault breathes with the rhythm of
 * intentional living."
 *
 * Reads from and writes to the Obsidian vault (or any markdown-based
 * second brain system). Generates daily summaries that can be filed
 * directly into the vault's daily notes structure.
 *
 * Architecture: Foundation-only. No SwiftUI. Fully type-checks with
 * swiftc -typecheck -sdk macosx. Uses filesystem-direct pattern.
 */

import Foundation

// MARK: - Vault Configuration

/// Represents the discovered Obsidian vault configuration.
struct VaultConfig: Codable {
    let name: String
    let path: String

    /// The daily notes directory, if it exists
    var dailyNotesURL: URL? {
        let url = URL(fileURLWithPath: path).appendingPathComponent("Daily")
        return FileManager.default.fileExists(atPath: url.path) ? url : nil
    }

    /// The journal directory, if it exists
    var journalURL: URL? {
        let url = URL(fileURLWithPath: path).appendingPathComponent("Journal")
        return FileManager.default.fileExists(atPath: url.path) ? url : nil
    }
}

// MARK: - Daily Summary Structure

/// A structured daily summary ready for vault filing.
struct VaultDailySummary: Codable, Identifiable {
    let id: UUID
    let date: Date
    let sessionsLogged: Int
    let totalFocusMinutes: Int
    let tasksCompleted: Int
    let practicesCompleted: [String]
    let toolsUsed: [String]
    let skillsLearned: [String]
    let mood: String
    let reflection: String
    let topDomains: [String]
    let generatedAt: Date

    init(
        date: Date = .now,
        sessionsLogged: Int = 0,
        totalFocusMinutes: Int = 0,
        tasksCompleted: Int = 0,
        practicesCompleted: [String] = [],
        toolsUsed: [String] = [],
        skillsLearned: [String] = [],
        mood: String = "neutral",
        reflection: String = "",
        topDomains: [String] = [],
        generatedAt: Date = .now
    ) {
        self.id = UUID()
        self.date = date
        self.sessionsLogged = sessionsLogged
        self.totalFocusMinutes = totalFocusMinutes
        self.tasksCompleted = tasksCompleted
        self.practicesCompleted = practicesCompleted
        self.toolsUsed = toolsUsed
        self.skillsLearned = skillsLearned
        self.mood = mood
        self.reflection = reflection
        self.topDomains = topDomains
        self.generatedAt = generatedAt
    }

    /// Formats the summary as markdown for vault filing.
    func toMarkdown() -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd"
        let dateStr = formatter.string(from: date)

        formatter.dateStyle = .full
        let fullDate = formatter.string(from: date)

        let hours = Double(totalFocusMinutes) / 60.0

        var md = """
        # 📅 \(fullDate)

        > *Auto-generated by AMOR on \(formattedGenerated)*

        ## 📊 Session Summary
        - **Sessions logged:** \(sessionsLogged)
        - **Focus time:** \(String(format: "%.1f", hours)) hours (\(totalFocusMinutes) min)
        - **Tasks completed:** \(tasksCompleted)
        - **Mood:** \(mood)

        """

        if !practicesCompleted.isEmpty {
            md += "## 🧘 Practices Completed\n"
            for practice in practicesCompleted {
                md += "- ✅ \(practice)\n"
            }
            md += "\n"
        }

        if !toolsUsed.isEmpty {
            md += "## 🛠️ Tools Used\n"
            for tool in toolsUsed {
                md += "- \(tool)\n"
            }
            md += "\n"
        }

        if !skillsLearned.isEmpty {
            md += "## 📚 Skills & Learning\n"
            for skill in skillsLearned {
                md += "- \(skill)\n"
            }
            md += "\n"
        }

        if !topDomains.isEmpty {
            md += "## 🏷️ Domains\n"
            for domain in topDomains {
                md += "- \(domain)\n"
            }
            md += "\n"
        }

        if !reflection.isEmpty {
            md += "## 💭 Reflection\n\(reflection)\n\n"
        }

        md += """
        ---
        **Tags:** #daily #amor #session-dump #\(dateStr)
        """

        return md
    }

    private var formattedGenerated: String {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        formatter.timeStyle = .short
        return formatter.string(from: generatedAt)
    }
}

// MARK: - Second Brain Manager

/// Manages the connection between AMOR and the user's second brain system.
///
/// Auto-discovers Obsidian vaults from common locations. Supports
/// reading existing daily notes and writing new summaries.
@Observable
final class AMORSecondBrainManager {

    // MARK: - Published State

    /// Whether a vault was discovered
    var isVaultAvailable: Bool = false

    /// The discovered vault configuration
    var vault: VaultConfig?

    /// Recently written summaries (for dashboard card)
    var recentSummaries: [VaultDailySummary] = []

    /// Whether the last write succeeded
    var lastWriteSucceeded: Bool = false

    /// Status message for UI
    var statusMessage: String = "Searching for vault…"

    // MARK: - Init

    init() {
        discoverVault()
    }

    // MARK: - Vault Discovery

    /// Searches common locations for an Obsidian vault.
    func discoverVault() {
        let home = FileManager.default.homeDirectoryForCurrentUser
        var candidates: [URL] = [
            home.appendingPathComponent("Documents/Obsidian Vault"),
            home.appendingPathComponent("Documents/ObsidianVault"),
            home.appendingPathComponent("Obsidian Vault"),
            home.appendingPathComponent("Documents/vault"),
            home.appendingPathComponent("Documents/Vault"),
        ]

        // Also check for .obsidian directory markers
        let documentsDir = home.appendingPathComponent("Documents")
        if let contents = try? FileManager.default.contentsOfDirectory(at: documentsDir, includingPropertiesForKeys: nil) {
            for item in contents where item.hasDirectoryPath {
                let obsidianConfig = item.appendingPathComponent(".obsidian")
                if FileManager.default.fileExists(atPath: obsidianConfig.path) {
                    candidates.append(item)
                }
            }
        }

        for candidate in candidates {
            if FileManager.default.fileExists(atPath: candidate.path) {
                self.vault = VaultConfig(
                    name: candidate.lastPathComponent,
                    path: candidate.path
                )
                self.isVaultAvailable = true
                self.statusMessage = "Vault: \(vault?.name ?? "")"
                return
            }
        }

        self.isVaultAvailable = false
        self.statusMessage = "No Obsidian vault found"
    }

    // MARK: - Daily Note Filename

    /// Generates the daily note filename for a date (Obsidian default format).
    func dailyNoteFilename(for date: Date) -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd"
        return formatter.string(from: date) + ".md"
    }

    // MARK: - Read Existing Daily Notes

    /// Reads existing daily notes from the vault (last N days).
    func readDailyNotes(daysBack: Int = 7) -> [(date: Date, content: String, path: String)] {
        guard let vault = vault else { return [] }

        var results: [(date: Date, content: String, path: String)] = []
        let calendar = Calendar.current

        // Check both "Daily" subdirectory and vault root
        let searchDirs: [URL] = [
            URL(fileURLWithPath: vault.path).appendingPathComponent("Daily"),
            URL(fileURLWithPath: vault.path).appendingPathComponent("Journal"),
            URL(fileURLWithPath: vault.path),
        ]

        for daysAgo in 0..<daysBack {
            if let date = calendar.date(byAdding: .day, value: -daysAgo, to: Date()) {
                let filename = dailyNoteFilename(for: date)

                for dir in searchDirs {
                    let fileURL = dir.appendingPathComponent(filename)
                    if let content = try? String(contentsOf: fileURL, encoding: .utf8) {
                        results.append((date: date, content: content, path: fileURL.path))
                        break // Found for this date
                    }
                }
            }
        }

        return results
    }

    // MARK: - Write Daily Summary

    /// Writes a daily summary to the vault as a daily note.
    /// If a note already exists for the date, appends AMOR data to it.
    func writeDailySummary(_ summary: VaultDailySummary) -> Bool {
        guard let vault = vault else {
            lastWriteSucceeded = false
            statusMessage = "No vault connected"
            return false
        }

        let vaultURL = URL(fileURLWithPath: vault.path)

        // Determine write directory (create Daily/ if it doesn't exist)
        let dailyDir = vaultURL.appendingPathComponent("Daily")
        if !FileManager.default.fileExists(atPath: dailyDir.path) {
            try? FileManager.default.createDirectory(at: dailyDir, withIntermediateDirectories: true)
        }

        let filename = dailyNoteFilename(for: summary.date)
        let fileURL = dailyDir.appendingPathComponent(filename)

        let markdown = summary.toMarkdown()

        if FileManager.default.fileExists(atPath: fileURL.path) {
            // Append to existing note
            if let existing = try? String(contentsOf: fileURL, encoding: .utf8) {
                let separator = "\n\n---\n\n"
                let combined = existing + separator + markdown
                do {
                    try combined.write(to: fileURL, atomically: true, encoding: .utf8)
                    lastWriteSucceeded = true
                    statusMessage = "Appended to \(filename)"
                } catch {
                    lastWriteSucceeded = false
                    statusMessage = "Write failed: \(error.localizedDescription)"
                    return false
                }
            }
        } else {
            // Create new note
            do {
                try markdown.write(to: fileURL, atomically: true, encoding: .utf8)
                lastWriteSucceeded = true
                statusMessage = "Created \(filename)"
            } catch {
                lastWriteSucceeded = false
                statusMessage = "Write failed: \(error.localizedDescription)"
                return false
            }
        }

        // Track recent summaries
        recentSummaries.insert(summary, at: 0)
        if recentSummaries.count > 10 {
            recentSummaries = Array(recentSummaries.prefix(10))
        }

        return true
    }

    // MARK: - List All Vault Notes

    /// Returns a listing of all markdown notes in the vault.
    func listVaultNotes(limit: Int = 100) -> [(path: String, title: String, modified: Date)] {
        guard let vault = vault else { return [] }

        let vaultURL = URL(fileURLWithPath: vault.path)
        var results: [(path: String, title: String, modified: Date)] = []

        enumerateMarkdownFiles(in: vaultURL, results: &results, limit: limit)

        return results.sorted { $0.modified > $1.modified }
    }

    private func enumerateMarkdownFiles(in dir: URL, results: inout [(path: String, title: String, modified: Date)], limit: Int) {
        guard results.count < limit else { return }

        // Skip .obsidian and other hidden directories
        let dirname = dir.lastPathComponent
        if dirname.hasPrefix(".") || dirname == ".obsidian" || dirname == ".trash" {
            return
        }

        guard let contents = try? FileManager.default.contentsOfDirectory(at: dir, includingPropertiesForKeys: [.contentModificationDateKey, .isDirectoryKey]) else {
            return
        }

        for item in contents {
            let isDir = (try? item.resourceValues(forKeys: [.isDirectoryKey]).isDirectory) ?? false

            if isDir {
                enumerateMarkdownFiles(in: item, results: &results, limit: limit)
            } else if item.pathExtension == "md" {
                let modified = (try? item.resourceValues(forKeys: [.contentModificationDateKey]).contentModificationDate) ?? Date.distantPast
                let title = item.deletingPathExtension().lastPathComponent
                let relativePath = item.path.replacingOccurrences(of: vault!.path + "/", with: "")
                results.append((path: relativePath, title: title, modified: modified))

                if results.count >= limit { return }
            }
        }
    }

    // MARK: - Read Note Content

    /// Reads the content of a specific note by relative path.
    func readNote(path: String) -> String? {
        guard let vault = vault else { return nil }
        let url = URL(fileURLWithPath: vault.path).appendingPathComponent(path)
        return try? String(contentsOf: url, encoding: .utf8)
    }
}
